### ISSUE TITLE
Use testlib.h to check the verdicts

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor#38]
**Is your feature request related to a problem? Please describe.**

Now the diff viewer works incorrectly for me, I guess it's about the newline character (I'm using Windows 10, and this happens only when there are more than one lines). And I have to follow a certain format strictly, even the space characters.

**Describe the solution you'd like**

Use testlib.h to check the verdicts. Users can choose one of [the default checkers](https://github.com/MikeMirzayanov/testlib/tree/master/checkers) by a drop-down box, and [wcmp](https://github.com/MikeMirzayanov/testlib/blob/master/checkers/wcmp.cpp) is the default one.

The details besides AC/WA can be shown in the "Compiler Messages and stderr" section.

**Describe alternatives you've considered**

Use something like `diff -b` to ignore spaces.

**Additional context**

N/A

**Comment by coder3101** [comment]
Line 826 in mainwindow.cc checks for first case, if they are equal or not. Similarly in following lines, it is checked.

I see due to \r\n and \n the issue is arising.

Instead of using, full testlib.h could we by our ownself implement `wcmp`, by having let's say a private member `bool wcmp(QString out, QString exp)`, then in those lines instead of doing `==`, we could call this function. 

If you want to put some error on message box, that could be done too, with `Log::MessageLogger::warn("Title","message");` inside that `wcmp` function.

**Comment by coder3101** [comment]
Since i don't know about this `wcmp`, comparison principles. You could by yourself implement it and change mainwindow.cc accordingly.

**Comment by ouuan** [comment]
Now only the alternative is implemented, but testlib.h is better. We can implement this now.

**Comment by coder3101** [comment]
Do it as you feel is okay, just make sure that AC/WA verdicts are different for each platform. Like codeforces doesn't care about "space separated" or "line separated", however some platforms are separator agnostic and fail on above  difference. We already had this discussion when you wrote `isPass()` function to check `verdict ()`

**Comment by ouuan** [comment]
Added in e2d5146818fdc7e8e568fd93c606022a494419c1.
