### ISSUE TITLE
Formatter error

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor#80]
**Describe the bug**

Formatter crashes unexpectedly.

**To Reproduce**

1. Open a new tab.
2. Make 3 new lines.
3. Format the code.
4. Get `[Format command returned non-zero exit code -1073741819]`.

It happens with a high probability, but not always for me.

**Expected behavior**

The formatter won't crash.

**Screenshots**

![image](https://user-images.githubusercontent.com/30581822/72164164-25f9e580-3400-11ea-98d5-40141ea67df5.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Version: cb333ed

**Smartphone (please complete the following information):**

N/A

**Additional context**

I think it happens because the file is occupied by the editor, and clang-format can't modify it.

I suggest using clang-format by its output, instead of the `-i` option. It will not only fix this bug, but also support undo for formatting.

I'll try to fix it tomorrow.

**Comment by coder3101** [comment]
It doesn't happen because of editor holding the file. The editor when it needs to format copies all content of editor to a temporary file and then clang format runs on it only after editor closes the files. After clang-format executes. The file is read and contents are made available to editor. See Formatter.cpp

clang-format -i was used because it saved me from reading clang-format stdout and redirecting to editor. Try if what you do works!
